services:
  hive-metastore:
    image: apache/hive:latest
    container_name: hive-metastore
    environment:
      - HIVE_METASTORE_PORT_NUMBER=9083
      - HIVE_METASTORE_DATABASE_NAME=data_db
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./hive/warehouse:/hive/data
    ports:
      - "9083:9083"

  presto:
    image: prestodb/presto:latest
    container_name: presto
    ports:
      - "8081:8081"
    volumes:
      - ./etc:/opt/presto/etc
    depends_on:
      - hive-metastore
